<a href="https://colab.research.google.com/github/umangnaith/Python_visualization_learnings/blob/main/Numpy_self.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing numpy:

for the environments where numpy is not there we use:

!pip install numpy

In [1]:
import numpy as np

In [2]:
a=[1,2,3,4,5]
type(a)

list

In [3]:
b=np.array(a)
type(b)

numpy.ndarray

to square each no using a list we had to iterate over each element and square it but with numpu we can just

In [4]:
b**2

array([ 1,  4,  9, 16, 25])

In [5]:
arr1 = np.array(range(1000000))
arr1.ndim # gives dimension of an array

1

In [6]:
arr1.shape #tells us number of elements across every dimension

(1000000,)

In [7]:
arr2 = np.array([[1, 2, 3], [4, 5, 6], [10, 11, 12]])
print(arr2)

[[ 1  2  3]
 [ 4  5  6]
 [10 11 12]]


In [8]:
arr2.ndim

2

In [9]:
arr2.shape

(3, 3)

In [10]:
arr2 = np.arange(1, 5)
arr2

array([1, 2, 3, 4])

In [11]:
arr2_step = np.arange(1, 5, 2)
arr2_step

array([1, 3])

In [12]:
arr3 = np.arange(1, 5, 0.5)
arr3

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [13]:
arr4=np.array([1,2,3,4.0])  #TYPE CONVERSION
arr4

array([1., 2., 3., 4.])

In [14]:
arr5=np.array(["A", 1, 2, 3])
arr5

array(['A', '1', '2', '3'], dtype='<U21')

In [15]:
arr5 = np.array([1, 2, 3, 4], dtype="float")
arr5

array([1., 2., 3., 4.])

In [16]:
arr=np.array([1,2,3,4])
arr = arr.astype('float64')
print(arr)

[1. 2. 3. 4.]


Indexing.

indexing is same as list

In [17]:
m1 = np.arange(12)
m1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
m1[0] # gives first element of array

0

In [19]:
m1[-1] # negative indexing in numpy array

11

In [20]:
m1 = np.array([100,200,300,400,500,600])
m1[[2,3,4,1,2,2]] # we can just give the indeices of the elements in the form of list to access them

array([300, 400, 500, 200, 300, 300])

If you want to extract multiple indices, you need to use two sets of square brackets [[ ]]
Otherwise, you will get an error.
Because it is only expecting a single index.
For multiple indices, you need to pass them as a list.

In [21]:
m1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
m1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

SLICING:Similar to Python lists

In [22]:
m1[:5]

array([1, 2, 3, 4, 5])

In [23]:
m1[-5:-1]

array([6, 7, 8, 9])

In [24]:
m1[-5: -1: -1]

array([], dtype=int64)

Masking

Numpy arrays can be indexed with boolean arrays (masks).

This method is called fancy indexing or masking.

In [25]:
m1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
m1 < 6

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [26]:
m1[[True,  True,  True,  True,  True, False, False, False, False, False]]

array([1, 2, 3, 4, 5])

In [27]:
m1[[True,  True,False, False,  True,  True,  True,  False, False, False]]

array([1, 2, 5, 6, 7])

Notice that we are passing a list of indices.

For every instance of True, it will print the corresponding index.

Conversely, for every False, it will skip the corresponding index, and not print it.

Now, let's use this to filter or mask values from our array.

Condition will be passed instead of indices and slice ranges.

In [28]:
m1[m1 < 6]

array([1, 2, 3, 4, 5])

In [29]:
m1[m1%2 == 0] #masking even values from our array

array([ 2,  4,  6,  8, 10])

Working with 2D arrays (Matrices):

In [30]:
a=np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [31]:
a.shape

(16,)

In [32]:
a.ndim

1

In [33]:
a.reshape(8, 2) #changes the shape of the array

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [34]:
a.reshape(4, 4) #whatever the shape we're trying to reshape to, must be able to incorporate the number of elements that we have.otherwise it will bw a Valueeorror

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [35]:
a.reshape(8, -1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [36]:
a = a.reshape(8, 2)
len(a)

8

In [37]:
len(a[0])

2

In [38]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
a.shape

(3, 4)

Transpose

In [40]:
a.T #to transpose the matrix

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [41]:
a.T.shape

(4, 3)

Indexing

In [42]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
a[1][2]   # to access 6 from this matrix

6

In [44]:
a[1, 2] #we can also write the above as this and this is more prefered

6

In [45]:
m1 = np.arange(9).reshape((3,3))
m1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [46]:
m1[[0,1,2],[0,1,2]] # picking up element (0,0), (1,1) and (2,2)

array([0, 4, 8])

Slicing in 2D arrays

In [47]:
m1=np.arange(12).reshape(3,4)
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
m1[:2] # gives first two rows.If we just give one argument it will consider it for rows

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [49]:
m1[:, :2] # gives first two columns.since rows are not specified it will consider all the rows

array([[0, 1],
       [4, 5],
       [8, 9]])

In [50]:
m1[:, 1:3] # gives 2nd and 3rd col

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

Fancy Indexing (Masking) in 2D arrays

In [51]:
m1=np.arange(12).reshape(3,4)
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
m1 < 6  #A matrix having boolean values True and False is returned.

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [53]:
m1[m1 < 6] #Values corresponding to True are retained. the matrix returned is 1d array

array([0, 1, 2, 3, 4, 5])

Aggregate Functions:

1D Array


In [54]:
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
np.sum(a) #sums all the values in a numpy array.

55

In [56]:
np.mean(a) # mean of all values in a numpy array.

5.5

In [57]:
np.min(a) #gives minimum value in a array

1

In [58]:
np.max(a) #gives max value in a array

10

2D Array

In [59]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
np.sum(a)

66

for 2d array aggregate funtions:

axis=0 means column wise operation

axis=1 means row wise operations

In [61]:
np.sum(a, axis=0) #gives sum of column and returns array containing sum of each row

array([12, 15, 18, 21])

In [62]:
np.sum(a, axis=1) # gives sum of rows

array([ 6, 22, 38])

Logical Operations:

**np.any()** - returns True if any of the corresponding elements in the argument arrays follow the provided condition.

In [63]:
# to check if we can buy anythind from a given shopping list
import numpy as np

prices = np.array([50, 45, 25, 20, 35]) #prices on the shopping list
budget = 30 #our budget

can_afford = np.any ( prices <= budget )

if can_afford:print("you have budget to buy atleast one item")
else: print("everything is unaffordalble")

you have budget to buy atleast one item


**np.all()** - returns True if all the elements in the argument arrays follow the provided condition.

In [64]:
#to make sure all the chores are done before you can play video games.
import numpy as np

chores=np.array([1,1,1,1,0])

chores_status=np.all(chores == 1)

if chores_status:
  print("Time to play")
else:
  print("Go finish the chores")

Go finish the chores


**.all()** - element wise comparision

In [65]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

((a <= b) & (b <= c)).all()

True

**np.where()**

np.where(condition, [x, y])

returns an ndarray whose elements are chosen from x or y depending on condition.

In [66]:
#you want to apply a 10% discount to all products with prices above $50.

import numpy as np

# Product prices
prices = np.array([45, 55, 60, 75, 40, 90])

# Apply a 10% discount to prices above $50
discounted_prices = np.where(prices > 50, prices * 0.9, prices)

print("Original prices:", prices)
print("Discounted prices:", discounted_prices)

Original prices: [45 55 60 75 40 90]
Discounted prices: [45.  49.5 54.  67.5 40.  81. ]


In [67]:
#given an array if element >0 change to +1 otherwise -1
arr = np.array([-3,4,27,34,-2, 0, -45,-11,4, 0 ])

arr[arr > 0]  = 1
arr [arr < 0] = -1

arr

array([-1,  1,  1,  1, -1,  0, -1, -1,  1,  0])

In [68]:
arr = np.array([-3,4,27,34,-2, 0, -45,-11,4, 0 ])
arr=np.where(arr>0,1,-1) # does the same as abpve
arr

array([-1,  1,  1,  1, -1, -1, -1, -1,  1, -1])