<a href="https://colab.research.google.com/github/umangnaith/Python_visualization_learnings/blob/main/Numpy_self.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing numpy:

for the environments where numpy is not there we use:

!pip install numpy

In [4]:
import numpy as np

In [5]:
a=[1,2,3,4,5]
type(a)

list

In [6]:
b=np.array(a)
type(b)

numpy.ndarray

to square each no using a list we had to iterate over each element and square it but with numpu we can just

In [7]:
b**2

array([ 1,  4,  9, 16, 25])

In [8]:
arr1 = np.array(range(1000000))
arr1.ndim # gives dimension of an array

1

In [9]:
arr1.shape #tells us number of elements across every dimension

(1000000,)

In [10]:
arr2 = np.array([[1, 2, 3], [4, 5, 6], [10, 11, 12]])
print(arr2)

[[ 1  2  3]
 [ 4  5  6]
 [10 11 12]]


In [11]:
arr2.ndim

2

In [12]:
arr2.shape

(3, 3)

In [13]:
arr2 = np.arange(1, 5)
arr2

array([1, 2, 3, 4])

In [14]:
arr2_step = np.arange(1, 5, 2)
arr2_step

array([1, 3])

In [15]:
arr3 = np.arange(1, 5, 0.5)
arr3

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [18]:
arr4=np.array([1,2,3,4.0])  #TYPE CONVERSION
arr4

array([1., 2., 3., 4.])

In [19]:
arr5=np.array(["A", 1, 2, 3])
arr5

array(['A', '1', '2', '3'], dtype='<U21')

In [20]:
arr5 = np.array([1, 2, 3, 4], dtype="float")
arr5

array([1., 2., 3., 4.])

In [23]:
arr=np.array([1,2,3,4])
arr = arr.astype('float64')
print(arr)

[1. 2. 3. 4.]


Indexing.

indexing is same as list

In [24]:
m1 = np.arange(12)
m1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
m1[0] # gives first element of array

0

In [26]:
m1[-1] # negative indexing in numpy array

11

In [27]:
m1 = np.array([100,200,300,400,500,600])
m1[[2,3,4,1,2,2]] # we can just give the indeices of the elements in the form of list to access them

array([300, 400, 500, 200, 300, 300])

If you want to extract multiple indices, you need to use two sets of square brackets [[ ]]
Otherwise, you will get an error.
Because it is only expecting a single index.
For multiple indices, you need to pass them as a list.

In [28]:
m1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
m1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

SLICING:Similar to Python lists

In [29]:
m1[:5]

array([1, 2, 3, 4, 5])

In [30]:
m1[-5:-1]

array([6, 7, 8, 9])

In [31]:
m1[-5: -1: -1]

array([], dtype=int64)

Masking

Numpy arrays can be indexed with boolean arrays (masks).

This method is called fancy indexing or masking.

In [32]:
m1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
m1 < 6

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [34]:
m1[[True,  True,  True,  True,  True, False, False, False, False, False]]

array([1, 2, 3, 4, 5])

In [33]:
m1[[True,  True,False, False,  True,  True,  True,  False, False, False]]

array([1, 2, 5, 6, 7])

Notice that we are passing a list of indices.

For every instance of True, it will print the corresponding index.

Conversely, for every False, it will skip the corresponding index, and not print it.

Now, let's use this to filter or mask values from our array.

Condition will be passed instead of indices and slice ranges.

In [35]:
m1[m1 < 6]

array([1, 2, 3, 4, 5])

In [37]:
m1[m1%2 == 0] #masking even values from our array

array([ 2,  4,  6,  8, 10])

Working with 2D arrays (Matrices):

In [39]:
a=np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [40]:
a.shape

(16,)

In [41]:
a.ndim

1

In [42]:
a.reshape(8, 2) #changes the shape of the array

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [44]:
a.reshape(4, 4) #whatever the shape we're trying to reshape to, must be able to incorporate the number of elements that we have.otherwise it will bw a Valueeorror

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [45]:
a.reshape(8, -1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [46]:
a = a.reshape(8, 2)
len(a)

8

In [47]:
len(a[0])

2

In [48]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
a.shape

(3, 4)

Transpose

In [50]:
a.T #to transpose the matrix

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [51]:
a.T.shape

(4, 3)

Indexing

In [52]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
a[1][2]   # to access 6 from this matrix

6

In [55]:
a[1, 2] #we can also write the above as this and this is more prefered

6